name: flutter_riverpod_template
description: A flutter boilerplate project with riverpod 2.0 containing riverpod annotations, freezed, lints, hive, easy_translations and more


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.5+1

environment:
  sdk: ">=3.0.5 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.11
  flutter_displaymode: ^0.6.0
  easy_localization: ^3.0.1
  ionicons: ^0.2.2
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  riverpod: ^2.3.6
  dio: ^5.2.1+1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.1.1
  hive: ^2.2.3
  retrofit: ^4.0.1
  logger: ^2.4.0
  injectable: ^2.1.2
  get_it: ^7.6.0
  hive_flutter: ^1.1.0
  get_storage: ^2.1.1
  gap: ^3.0.1
  network_logger: ^1.0.4
  json_annotation: ^4.8.1
  go_router: ^14.0.2
  fpdart: ^1.1.0
  connectivity_plus: ^6.0.2
  responsive_builder: ^0.7.0
  flex_color_scheme: ^7.1.2
  liquid_pull_to_refresh: ^3.0.1
  url_launcher: ^6.1.11
  intl: ^0.19.0
  flutter_html: ^3.0.0-beta.2
  flutter_swipe_action_cell: ^3.1.2
  stack_trace: ^1.11.0
  water_drop_nav_bar: ^2.2.0+5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  # The "build_runner" package provides a way to generate files using Dart code
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.3.2
  retrofit_generator: ^8.0.3
  injectable_generator: ^2.1.6
  hive_generator: ^2.0.0
  freezed: ^2.3.5
  rider: ^0.0.1
  flutter_gen: ^5.7.0


flutter:


  uses-material-design: true

  assets:
    - assets/translations/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
